### ISSUE TITLE
Can I get the color change during the listening process？

### ISSUE THREAD

**Issue by NicodeLee** [skydoves/ColorPickerView#1]
Thanks for you job.

**Comment by NicodeLee** [comment]
I get it,thanks.

**Comment by ayushigpt** [comment]
i want that when i click on imageview(in which i saved the background color),indicator of color picker itself move on that color which i previously saved .How i can achieve it by your library??

**Comment by skydoves** [comment]
@ayushigpt I'm sorry about the late reply.
on v1.0.1 you can move selector's points as using colorPickerView.setSelectorPoint(int x, int y) method.

**Comment by ayushigpt** [comment]
@skydoves colorPickerview.setSelectorPoint(int x,int y) method not working fine when i touch the imageview (where i saved my color) to find that color on palette  but the selector of palette  going outside the palette  .Selector should be remain inside the palette  and indicate that color but i should not
Please reply as soon as possible

**Comment by skydoves** [comment]
I'm sorry about the late reply.It fixed. Thank you. 
 
-----Original Message-----

**Comment by rameshjilla** [comment]
Hi ,
How can i get the X and Y coordinates colorlistener?

**Comment by ayushigpt** [comment]
@rameshjilla 
You can get it by using setOnTouchListener and   onTouch have parameter MotionEvent.From MotionEvent object you can  getX() and getY()
