### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [skydoves/ColorPickerView#11]
Good day @skydoves  I am a graphic designer and i would like to contribute to your nice project by designing a logo for it. I will be doing it for free, if you will permit me i will start my design immediately. Thanks and best regards! - Tobaloidee

**Comment by skydoves** [comment]
@Tobaloidee 
Sorry for the late reply.
Could you consider for contributing [PowerMenu](https://github.com/skydoves/PowerMenu) repository as logo design?

**Comment by Tobaloidee** [comment]
Hello @skydoves  I will think of a logo design for that PowerMenu repo..will post my initial output there and create an issue also..how about on this repo?

**Comment by Tobaloidee** [comment]
I already made a design for PowerMenu. I opened an issue there 👍
