### ISSUE TITLE
Vertical orientation for sliders?

### ISSUE THREAD

**Issue by kiwiandroiddev** [skydoves/ColorPickerView#16]
Just wondering if vertical sliders is something you had in mind to add support for, or have already planned? And if not, would you be open to a PR?
Cheers, and thanks again for this library.

**Comment by skydoves** [comment]
@kiwiandroiddev 
Sorry for late reply.
Not planned yet about the vertical slider.
Of course, you can PR to this repository!
Thank you so much about interested in this repository :)
