### ISSUE TITLE
Can we set the Image Resource via Java Code ?

### ISSUE THREAD

**Issue by IAmSarthakVerma** [skydoves/ColorPickerView#2]
I want to set the app:src="@drawable/image" via java code. Please help me regarding this.

**Comment by skydoves** [comment]
@IAmSarthakVerma I'm sorry about the late reply.
on v1.0.1 you can change palette and selector drawable resource as using 
colorPickerView.setPaletteDrawable(Drawable drawable)
colorPickerView.setSelectorDrawable(Drawable drawable)
method.
thanks!

**Comment by IAmSarthakVerma** [comment]
Thank you @skydoves

**Comment by IAmSarthakVerma** [comment]
@skydoves I am now able to select the palette image from java code but after that I am not able to use the color listener .

**Comment by skydoves** [comment]
@IAmSarthakVerma  I'm sorry about the late reply. 
It fixed. Thank you.

**Comment by IAmSarthakVerma** [comment]
No Problem! I'll try to implement it soon! 
Thank you for your support :)  <3
