### ISSUE TITLE
setACTON_UP working incorrectly after attaching BrightnessSlider

### ISSUE THREAD

**Issue by iMJ007** [skydoves/ColorPickerView#21]
The `setACTON_UP(true)` method worked correctly without using brightness slider, but after attaching brightness slider the color listener keeps triggering even when while dragging the selector.

And another issue is setting `setACTION_UP(true)` while brightness slider attached prevents he selector from moving while dragging. It changes position when finger is released.

**Comment by skydoves** [comment]
resolved https://github.com/skydoves/ColorPickerView/pull/22
