### ISSUE TITLE
How to convert the color value to the coordinate value on the disc

### ISSUE THREAD

**Issue by kexuebiao** [skydoves/ColorPickerView#23]
How to convert the color value to the x, y coordinate value on the ColorPickerView
for example color "#FF0000" to (x,y)

**Comment by kexuebiao** [comment]
I found an algorithm that swaps the color values into hsv and then calculates the coordinates.

int color = Color.BLUE;
int radius = mColorPickerView.getWidth() / 2;
Point point = color2Point(color, radius);
mColorPickerView.setSelectorPoint(point.x, point.y);

private Point color2Point(int color, float radius) {
        float[] hsv = new float[3];
        Color.colorToHSV(color, hsv);

        double x = hsv[1] * Math.cos(Math.toRadians(hsv[0]));
        double y = hsv[1] * Math.sin(Math.toRadians(hsv[0]));

        int pointX = (int) ((x + 1) * radius);
        int pointY = (int) ((1 - y) * radius);
        return new Point(pointX, pointY);
}

**Comment by skydoves** [comment]
@kexuebiao 
Thank you for your solution!
It will be implemented on next release.
I will release the next version tomorrow :)
