### ISSUE TITLE
Brightness slider bar not working properly

### ISSUE THREAD

**Issue by AntonisKl** [skydoves/ColorPickerView#29]
The brightness slider bar wheel cannot be dragged. Xml code (which is inside a LinearLayout):
        <com.skydoves.colorpickerview.sliders.BrightnessSlideBar
            android:id="@+id/brightnessSlide"
            android:layout_width="wrap_content"
            android:layout_height="280dp"
            android:layout_gravity="center"
            android:layout_marginLeft="15dp"
            android:layout_marginRight="10dp"
            app:borderColor_BrightnessSlider="@android:color/darker_gray"
            app:borderSize_BrightnessSlider="0"
            app:selector_BrightnessSlider="@drawable/wheel" />

**Comment by skydoves** [comment]
Hi!
It seems you want to implement the slider bar vertically.
In that case, you should use the below attribute than sizing height.

```gradle
android:rotation="90"
```

**Comment by AntonisKl** [comment]
Hi
It seems that android:rotation="90" is not working correctly.
![image](https://user-images.githubusercontent.com/18524649/52911943-30c0fe80-32b3-11e9-8103-7a4fa040891d.png)

**Comment by skydoves** [comment]
@AntonisKl 
Thank you for trying!
I really hope your project being well!
Thank you.
