### ISSUE TITLE
Issue when upgrading project to androidx to support the newest release version

### ISSUE THREAD

**Issue by AntonisKl** [skydoves/ColorPickerView#30]
When I changed my project's gradle files to support androidx and android api v28 I faced some problems and now my app cannot run. Is it possible to use the newest release version of this library (2.1.0) without migrating to androidx?

**Comment by skydoves** [comment]
Hi!
If your project is not migrated to AndroidX, you can use `v2.0.1`.
There is not much difference to `v2.1.0`.
Thank you.
