### ISSUE TITLE
Some incorrect behavior of getColorFromBitmap

### ISSUE THREAD

**Issue by yccheok** [skydoves/ColorPickerView#32]
**Please complete the following information:**
- Library Version [Master branch till 13 March 2019]
- Affected Device(s) [All]
 
**Describe the Bug:**

Suspicious logic of `getColorFromBitmap`

Hi, I'm refering to the code of `ColorPickerView`'s `getColorFromBitmap`.

```
  protected int getColorFromBitmap(float x, float y) {
    Matrix invertMatrix = new Matrix();
    palette.getImageMatrix().invert(invertMatrix);

    float[] mappedPoints = new float[] {x, y};
    invertMatrix.mapPoints(mappedPoints);

    if (palette.getDrawable() != null
        && palette.getDrawable() instanceof BitmapDrawable
        && mappedPoints[0] > 0
        && mappedPoints[1] > 0
        && mappedPoints[0] < palette.getDrawable().getIntrinsicWidth()
        && mappedPoints[1] < palette.getDrawable().getIntrinsicHeight()) {

      invalidate();

      Rect rect = palette.getDrawable().getBounds();
      float scaleX = mappedPoints[0] / rect.height();
      int x1 = (int) (scaleX * ((BitmapDrawable) palette.getDrawable()).getBitmap().getHeight());
      float scaleY = mappedPoints[1] / rect.width();
      int y1 = (int) (scaleY * ((BitmapDrawable) palette.getDrawable()).getBitmap().getWidth());
      return ((BitmapDrawable) palette.getDrawable()).getBitmap().getPixel(x1, y1);
    }
    return 0;
  }

```

I can understand the purpose of code till `invertMatrix.mapPoints(mappedPoints);`. It is converting `ImageView` coordinate, to `Drawable` coordinate.

However, I do suspect some correctness after `invertMatrix.mapPoints(mappedPoints);`. My understanding is, they are trying to convert `Drawable` coordinate, to `Bitmap` coordinate.

1) Instead of `mappedPoints[0] > 0 && mappedPoints[1] > 0`, should they be `mappedPoints[0] >= 0 && mappedPoints[1] >= 0` since 0 is a valid value for `Drawable` coordinate`.

2) Instead of `float scaleX = mappedPoints[0] / rect.height();`, should it be `float scaleX = mappedPoints[0] / rect.width();` ?

3) Instead of ` int x1 = (int) (scaleX * ((BitmapDrawable) palette.getDrawable()).getBitmap().getHeight());`, should it be ` int x1 = (int) (scaleX * ((BitmapDrawable) palette.getDrawable()).getBitmap().getWidth());`

4) Same concern goes to `float scaleY` and `int y1`

5) I expect if I click on top of the circle, I will get `int y1` almost equal to 0. However, the smallest value I can get is 56. Please see the following screenshot

<img width="210" alt="x" src="https://user-images.githubusercontent.com/308276/54287285-54404600-45e0-11e9-9d06-14391ba14069.png">

**Expected Behavior:**

I expect if I click on left most, I can get `int x1` almost equal to 0. And if I click on top most, I can get `int y1` almost equal to 0.

**Comment by yccheok** [comment]
Sorry. After I look at the source image, I notice there are some transparency area as the padding for color circle.

<img width="632" alt="xx" src="https://user-images.githubusercontent.com/308276/54289996-26a9cb80-45e5-11e9-8b6f-9bdbf471aea7.png">

But, my concern on point 1 till point 4 are still valid.

**Comment by skydoves** [comment]
@yccheok 
Thank you for your efforts! 👍
