### ISSUE TITLE
Dragging off of the view causes unexpected behavior

### ISSUE THREAD

**Issue by arislomovic** [skydoves/ColorPickerView#37]
If you drag your finger off of the color picker, the color listeners fire off many different colors and then eventually fire off transparent, giving a flicker appearance. I found this out by hooking it up to textview, having it update colors every time onColorSelected gets called.

**Comment by arislomovic** [comment]
Seems you addressed this

**Comment by skydoves** [comment]
@arislomovic 
Sorry for the late reply.
It seems the palette issue. #32 
If there are some transparency area as the padding for color circle, the listener would fire off transparent value.
