### ISSUE TITLE
Usage failure selectByHsv，

### ISSUE THREAD

**Issue by EmakefunAurora** [skydoves/ColorPickerView#38]
**Please complete the following information:**
- Library Version 2.1.1
- Affected Device(s) [millet 5s with Android 8.0]
 
**Describe the Bug:**
Hello, I call the method [colorPickerView. selectByHsv (color)]. It was found that [selectedColor = getColorFromBitmap (x, y);] This line of code always gets a value of 0. Excuse me, why is this?

**Expected Behavior:**
I expect to specify the position of the palette with the color as the parameter

![image](https://user-images.githubusercontent.com/49056966/57901977-cad81900-7899-11e9-835a-b34baa54165b.png)

**Comment by skydoves** [comment]
@EmakefunAurora 
The `selectByHsv` method will works correctly on version `2.1.4`!
Thank you for your issue :)

**Comment by EmakefunAurora** [comment]
Thank you for your reply. This method of selectByHsv can be used normally, but there seems to be some problems in accuracy. What's the solution, please?
![image](https://user-images.githubusercontent.com/49056966/58537293-2e146480-8225-11e9-9aba-47a814476638.png)
![image](https://user-images.githubusercontent.com/49056966/58537367-5a2fe580-8225-11e9-8166-a35d006880e4.png)
![image](https://user-images.githubusercontent.com/49056966/58537616-cb6f9880-8225-11e9-8d67-337768add61a.png)
![image](https://user-images.githubusercontent.com/49056966/58537808-3d47e200-8226-11e9-9b99-b7882a7b2296.png)

**Comment by JaeHunJang** [comment]
In my opinion, the palette used is a problem.
After testing, we found a similar solution in the following palette.
![palette_hsv3_c](https://user-images.githubusercontent.com/46174355/58684646-d6583380-83b3-11e9-9029-312e89e44ee1.png)

**Comment by arislomovic** [comment]
> **Please complete the following information:**
> 
> * Library Version 2.1.1
> * Affected Device(s) [millet 5s with Android 8.0]
> 
> **Describe the Bug:**
> Hello, I call the method [colorPickerView. selectByHsv (color)]. It was found that [selectedColor = getColorFromBitmap (x, y);] This line of code always gets a value of 0. Excuse me, why is this?
> 
> **Expected Behavior:**
> I expect to specify the position of the palette with the color as the parameter
> 
> ![image](https://user-images.githubusercontent.com/49056966/57901977-cad81900-7899-11e9-835a-b34baa54165b.png)

Hi,

Did you get this working? I updated to 2.1.4 and am still seeing this issue. The pointer always ends up at the center of the color picker.

**Comment by skydoves** [comment]
@EmakefunAurora 
Sorry for the late reply.
It is released a new version `2.1.5`.
I think it seems working correctly.
But there is a constraint for using the `selectByHsv` method.
The palette should be used the [default palette](https://github.com/skydoves/ColorPickerView/blob/master/colorpickerview/src/main/res/drawable/palette.png) in the internal ColorPickerView.
And [here](https://github.com/skydoves/ColorPickerView/tree/master/app) is the demo project.
Thank you for your issue and comment to me if the solution still has some problems. :)

**Comment by EmakefunAurora** [comment]
Hello, the problem has been solved, the effect is very good, thank you for your reply. I have a little suggestion. At present, the color progress bar in the frame only supports horizontal sliding. Why not add a vertical sliding mode to the progress bar? In this way, the framework can increase its scope of application.



aurora@emakefun.com
 
发件人： Jaewoong Eum
发送时间： 2019-06-15 00:42
收件人： skydoves/ColorPickerView
抄送： EmakefunAurora; Mention
主题： Re: [skydoves/ColorPickerView] Usage failure selectByHsv， (#38)
@EmakefunAurora
Sorry for the late reply.
It is released a new version 2.1.5.
I think it seems working correctly.
But there is a constraint for using the selectByHsv method.
The palette should be used the default palette in the internal ColorPickerView.
And here is the demo project.
Thank you for your issue and comment to me if the solution still has some problems. :)

**Comment by skydoves** [comment]
@EmakefunAurora 
You can show the slide bar vertically using the below method.
```xml
android:rotation="90"
```

**Comment by EmakefunAurora** [comment]
@Jaewoong Eum
I guess I didn't make it clear. You may have misunderstood what I meant. It is no problem to place the color progress bar vertically. The problem is that the color goes into the bar [selector_image], which slides left and right when the bar is placed horizontally, which is normal. Then I put the progress bar vertically. It still slides left and right. It's not the vertical up-down sliding I imagined. Is there any way to do this?


aurora@emakefun.com
 
发件人： Jaewoong Eum
发送时间： 2019-06-18 01:22
收件人： skydoves/ColorPickerView
抄送： EmakefunAurora; Mention
主题： Re: [skydoves/ColorPickerView] Usage failure selectByHsv， (#38)
@EmakefunAurora
You can show the slide bar vertically using the below method.
android:rotation="90"
―

**Comment by skydoves** [comment]
@EmakefunAurora 
I think you should set the width clearly like below.

```gradle
<com.skydoves.colorpickerview.sliders.AlphaSlideBar
        android:id="@+id/alphaSlideBar"
        android:layout_width="250dp"
        android:layout_height="wrap_content"
        android:rotation="90" 
        app:borderColor_AlphaSlideBar="@android:color/darker_gray"
        app:borderSize_AlphaSlideBar="5"
        app:selector_AlphaSlideBar="@drawable/wheel" />
```

Or If the example has still a problem could you make me a sample project?
