### ISSUE TITLE
setSelectorPoint() method is not working

### ISSUE THREAD

**Issue by dheadrick1618** [skydoves/ColorPickerView#39]
Using colorpickerpreference library version 1.0.4

Using an LG G6 smartphone.
 
I am using a ColorpickerView in one of my fragments.

Calling setSelectorPoint in onCreate of my fragment does not change the selector point. I am storing the X and Y selector point float values using the getSelectorX() and getSelectorY() methods when onDetach is called. When the fragment is closed and re-opened I typecast the selected float x and y values to integers, then pass them through the setSelectorPoint() method. 

I have confirmed the x/y values are being stored and retrieve correctly by the fragment, although the selector always initializes at the center point regardless...

Thank you for the library! Hope we can get this resolved.

**Comment by skydoves** [comment]
@dheadrick1618  
The `setSelectorPoint` method will works correctly on version `2.1.4`!
And you can use the `setPreferenceName` and `setLifecycleOwner`.
It will save the selectors position, colors following lifecycle and restore it automatically. 
Thank you for your issue :)

**Comment by dheadrick1618** [comment]
Thank you for getting back to me so quickly! 

I apologize for the noob question, but here it is. I am only using main activity in my app so I cannot use onSavedInstanceState with my fragments because their parent activity is never destroyed and thus never calls it.... That being said I have created two methods in my main activity to get and set various UI element values, essentially saving and restoring the value of each UI element (various seekbars and your colorpickerview). How does this relate to setPreferenceName & setLifeCycleOwner? I was just going store the selector x/y values when the fragment is destroyed and then when the fragment is opened in onCreate I would retrieve those values and then set the selector accordingly. 

Thank you very much for the help.

**Comment by skydoves** [comment]
@dheadrick1618 
Then you can save and restore using the below methods.

#### restoring properties
```java
.setPreferenceName("name")
```

#### saving properties manually
```java
ColorPickerPreferenceManager.getInstance(getContext()).saveColorPickerData(colorPickerView);
```
