### ISSUE TITLE
Selector not moving 

### ISSUE THREAD

**Issue by MuhammadaliMS** [skydoves/ColorPickerView#44]
**Please complete the following information:**
- Library Version [e.g. v2.1.0]
- Affected Device(s) []
 I am using oneplus six running on android 10
**Describe the Bug:**
I have implemented the colorpickerview in viewpager and it seems to be working fine as long as the colorpickerview is in the starting page of the view pager. If the colorpickerview is implemented in any other page , the selectors does not move. Everything else like colorpickerlistner works but the selector does not move due to some reason. Can you provide me some insights on how to solve this issue

**Expected Behavior:**

Selector should move on touch

**Comment by skydoves** [comment]
Hi, @MuhammadaliMS sorry for the late reply.
It seems your `ViewPager` has a focus on `onTouch` or `onClick` instead of the `ColorPickerView`.
Could you build using the below codes and a new version `2.2.1`?

`onViewCreated`
```kotlin
colorPickerView.setFocusableInTouchMode(true);
colorPickerView.requestFocus();
```
