### ISSUE TITLE
The color will flash when the touch point moves outside the color plate.

### ISSUE THREAD

**Issue by SuhaylZhao** [skydoves/ColorPickerView#46]
- Library Version [v2.1.6]
 
**Describe the Bug:**

1. When the touch point moves inside the color plate, everything works normally.
2. However, the color will flash when the touch point moves outside the color plate.

What happened and What should I do?

**Comment by skydoves** [comment]
@SuhaylZhao 
Hi, could you test with another image?
The basic palette's outline is not smooth.

**Comment by SuhaylZhao** [comment]
@skydoves 
Hi, I tried other image and got the same result. 

This has nothing to do with whether the color is smooth or not, but returns the wrong color value when the touch point moves to the outside of the color plate.  

I recorded the screen, and you can see clearly that he's blinking.

[2020-04-23_18-42-10.zip](https://github.com/skydoves/ColorPickerView/files/4521926/2020-04-23_18-42-10.zip)

**Comment by SuhaylZhao** [comment]
Hi,

You're right. The edge of the palette is not smooth enough.
I use the previous version of the palette, everything is working properly.

thank you.
