### ISSUE TITLE
Manifest Merger Failed

### ISSUE THREAD

**Issue by dheadrick1618** [skydoves/ColorPickerView#47]
Version 2.1.6
Using Samsung Galaxy s9
 
After creating a brand new android studio project (java) and changing nothing, I have added your library dependency to my apps build.gradle module as outlined at the beginning of your README. When I try to build the app (with absolutely no changes to a blank new project, just having added your dependency), I get the following error and the project will not build properly:

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-20:19 to override.

I tried adding 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml  as the suggestion mentioned but this also results in many more errors.

I also found online what appeared to be a solution, by adding the following lines to my gradle.properties file.

android.useAndroidX=true
android.enableJetifier=true

Although doing this now results in many more errors, such as my MainActivity being highlighted red and considered an error while anything having to do with AppCompatActivity is also an error....

I don't really know how to go about fixing this, as I am working in a completely brand new unchanged project with one empty main activity. Apologies as I have never worked with androidX before and do not really understand how the AppCompat stuff works.

Thank you

**Comment by skydoves** [comment]
Hi,
It looks you need to add "androidx.appcompat:appcompat:1.1.0" dependency on your gradle file.
And you can run using the [demo project](https://github.com/skydoves/ColorPickerView/tree/master/app) before constructing your environment.
Thank you.

**Comment by dheadrick1618** [comment]
Thank you this did solve my issue. I have not touched android studio in a few months and I didn't follow on the new Android X updates.
