### ISSUE TITLE
Kotlin implementation planned?

### ISSUE THREAD

**Issue by marcauberer** [skydoves/ColorPickerView#49]
Hi,
are there any plans for an implementation in Kotlin?

**Comment by skydoves** [comment]
@marcauberer 
Hi, you can use this library in Kotlin project.
Thanks :)

**Comment by marcauberer** [comment]
@skydoves 
Yes, I know (I already do). Google pushes Android apps towards the "Kotlin first" attitude, which implies, that developers should convert their projects (and libraries) to Kotlin.
So my question: Is there anything against a re-implementation in Kotlin?

**Comment by skydoves** [comment]
You don't need to re-implementation in Kotlin.
Just import to your project via Gradle.
[This project](https://github.com/skydoves/all-In-One) is using this library without any re-implementation.

**Comment by marcauberer** [comment]
Yes. This was not the point. I'm already using your lib in a [Kotlin project](https://github.com/ChilliBits/color-converter). My question is, if you're planning to convert **your lib** to Kotlin in the future?

**Comment by skydoves** [comment]
Ah, do you mean re-implementation whole codes in Kotlin this library?
I don't have any plans yet but If I have some free time, I will try.

**Comment by marcauberer** [comment]
Great! Thank you. Sorry for the confusion ;)

**Comment by skydoves** [comment]
It's okay. Thanks for your issue and good conversations :)
