### ISSUE TITLE
custom number of selectPoints for photos [request]

### ISSUE THREAD

**Issue by angelkoh** [skydoves/ColorPickerView#5]
can i request for multiple/custom number of select points (e.g. 3 or 5 points) for photos? 

something like the following. 
![maxresdefault](https://user-images.githubusercontent.com/829758/30092062-6341b026-92ef-11e7-92c4-c2e81b7db67b.jpg)

**Comment by skydoves** [comment]
In version 1.0.6 updated Multi-ColorPickerView.
You can reference example codes at below.
https://github.com/skydoves/ColorPickerView
