### ISSUE TITLE
DialogBuilder must override create() and not show()

### ISSUE THREAD

**Issue by Jean-Daniel** [skydoves/ColorPickerView#50]
**Please complete the following information:**
- Library Version: 2.1.6
 
**Describe the Bug:**

The ColorPickerDialog.Builder performs a lot of customisation in show, which is wrong, as it make it behave erroneously when using the create() method to build the dialog and displaying it afterward.

Actually, the base DialogBuilder show methods just call create() to build the dialog and then invoke show() to display it.

So overriding `create` to perform the dialog creation and customisation instead of `show` would cleanly solve the issue.

**Expected Behavior:**

When using the DialogBuilder create method, the resulting dialog should be properly configured and not ignore all my customisations (like hiding the alpha slider).

**Comment by skydoves** [comment]
Hi, @Jean-Daniel, Sorry for the late reply.
This issue will be included in the next version.
Thank you for sharing your issue!

**Comment by skydoves** [comment]
It is released in the new version `2.1.7`!
Thank you for your issue :)
