### ISSUE TITLE
Add initColor method

### ISSUE THREAD

**Issue by Lasicaine** [skydoves/ColorPickerView#53]
Hello! Could you please add initColor method  for ColorPickerDialog builder's for initialize set start color for ColorPickerView? 

For example:

new ColorPickerDialog.Builder(this)
      .setTitle("ColorPicker Dialog")
      .setPreferenceName("MyColorPickerDialog")
      .setPositiveButton(getString(R.string.confirm),
          new ColorEnvelopeListener() {
              @Override
              public void onColorSelected(ColorEnvelope envelope, boolean fromUser) {
                  setLayoutColor(envelope);
              }
          })
       .setNegativeButton(getString(R.string.cancel),
          new DialogInterface.OnClickListener() {
              @Override
              public void onClick(DialogInterface dialogInterface, int i) {
                  dialogInterface.dismiss();
              }
           })
      .attachAlphaSlideBar(true) // the default value is true.
      .attachBrightnessSlideBar(true)  // the default value is true.
      .setBottomSpace(12) // set a bottom space between the last slidebar and buttons.
      .setInitColor(here color in Int or Hex) // This method is neeeded for set initialize color.     <------------
      .show();

**Comment by skydoves** [comment]
Hi, @Lasicaine!
Thank you for your issue.
I will add some methods and attributes related to `initialColor`.
But you can implement it using the below method.

```java
colorPickerView.post(new Runnable() {
      @Override public void run() {
        try {
          selectByHsvColor(color);
        } catch (IllegalAccessException e) {
          e.printStackTrace();
        }
      }
    });
```

**Comment by Lasicaine** [comment]
Great! Thank you!

**Comment by skydoves** [comment]
Hi, @Lasicaine !
It is released in the new version [2.2.0](https://github.com/skydoves/ColorPickerView/releases/tag/2.2.0)
Thanks for your issue :)

**Comment by rolud** [comment]
Hello @skydoves! In version [2.2.2](https://github.com/skydoves/ColorPickerView/releases/tag/2.2.2) I don't find any initColor method for ColorPickerDialog.Builder. Is there an alternative method?

**Comment by skydoves** [comment]
Hi, @rolud 
You might use the below method.
```java
ColorPickerView colorPickerView = builder.getColorPickerView();

// set an initial position of the selector using a specific color. This attribute will work with only a default HSV palette.
colorPickerView.setInitialColor(color);
```
