### ISSUE TITLE
I want to set a color in the palette.

### ISSUE THREAD

**Issue by Astar75** [skydoves/ColorPickerView#55]
Is it possible to set the desired color in a custom palette?
I read that setInitialColor() can only work if there is a default palette, but I would like to find a way to set it on a custom palette. Maybe you can suggest an implementation?

**Comment by skydoves** [comment]
Unfortunately, searching specific coordinates using a specific color in a custom palette is impossible now. 
The `setInitialColor` only works in the HSV color model.

**Comment by Astar75** [comment]
The problem goes to the fact that the other fragment that uses the fine-tuning of the color must be linked to another fragment that uses your library.
And so I also thought to keep the position of the colors.
Well, if, for example, take an image and use the fore loop to go through the pixels comparing with the color, and if you find it, then set the selector there?
