### ISSUE TITLE
selecting color by hsv value fails

### ISSUE THREAD

**Issue by oltdaniel** [skydoves/ColorPickerView#57]
**Please complete the following information:**
- Library Version: `2.2.1`
- Affected Device(s) `Samsung Galaxy S9 with Android 10`
- Android Target SDK: `Android 10 (API Level 30, min: 29)` 
- Project uses Kotlin

**Describe the Bug:**

Selecting a color by its HSV value fails with `.selectByHsvColor(c)`. The error message references to `.setHsvPaletteDrawable()` which fails too. The color `c` is the value part (index 2) of `Color.RGBToHSV(...)`.

- Error Message of `.selectByHsvColor(c)`:
  `java.lang.IllegalAccessException: selectByHsvColor(@ColorInt int color) can be called only when the palette is an instance of ColorHsvPalette. Use setHsvPaletteDrawable();`

- Error Message of `.setHsvPaletteDrawable()`:
  `java.lang.IllegalArgumentException: width and height must be > 0`

**Expected Behavior:**

Selecting a color should be possible as mentioned in the examples.

**Comment by skydoves** [comment]
Hi, @oltdaniel 
As you can see from the log, the `selectByHsvColor` used with only `HsvPaletteDrawable`.
If you use other palette image or resources, can not use the method.

**Comment by simon-vajda** [comment]
I ran into the same problem. I'm not using a custom palette, and it still throws this error. If I check the `isHuePalette()` method, it returns false. In the layout file, it only has the id, height and width parameters, and in the code I just initialize a variable with `findViewById()`, and call the `selectByHsvColor()` and `isHuePalatte()` methods. (Target SDK: Android 10)
