### ISSUE TITLE
setSelector(x, y) doesn't work? 

### ISSUE THREAD

**Issue by mcdaryo** [skydoves/ColorPickerView#6]
I can't change position of custom selector. It is always in center of view.
Also, setSelectorDrawable() not working..
Anyone know what's the problem?

**Comment by skydoves** [comment]
Hello, isn't your custom selector's size bigger than palette?

**Comment by mcdaryo** [comment]
No, it's not. It's a small circle icon, 32x32 in hdpi. Values of x and y of colorView is always same.

**Comment by skydoves** [comment]
https://github.com/skydoves/ColorPickerView
This project includes some examples. Doesn't work properly?

**Comment by mcdaryo** [comment]
Strange...after I added some delay of 0ms > when call setSelectorPoint(), it works..
Thanks anyway
