### ISSUE TITLE
Colour/Brightness Picker option from Camera

### ISSUE THREAD

**Issue by HashirLabs** [skydoves/ColorPickerView#62]
**Is your feature request related to a problem?**

I cant pick a colour from a live camera

**Describe the solution you'd like:**

Looking for a colour picker and colour temprature/brightness picker option using live camera of the mobile device

**Describe alternatives you've considered:**

I saw below library, however it is very old, i feel many improvements can be added to this, having such option to existing colour picker would be a great addition

[CameraColorPicker](https://github.com/tvbarthel/CameraColorPicker)

**Comment by skydoves** [comment]
This feature is as huge as creating a new library, so not planning to support it yet.
Thanks for sharing your idea.
