### ISSUE TITLE
Listener always return Black color (#FF000000) if colorPickerView.setInitialColor is also Black

### ISSUE THREAD

**Issue by illwiz** [skydoves/ColorPickerView#65]
- Library Version = 2.2.2
- Affected Device(s) = Tested on Emulator Pixel 2 API 29
 
I use the library like this
```
val colorPickerDialog = ColorPickerDialog.Builder(requireContext())
                .setTitle("Color Picker")
                .setPositiveButton("OK",
                    object : ColorEnvelopeListener {
                        override fun onColorSelected(envelope: ColorEnvelope?, fromUser: Boolean) {
                            if(envelope==null) return
                            // Envelope color is #FF000000 although I selected different colors like Red/Yellow/etc
                        }
                    })
                .setNegativeButton("Cancel") { dialog, _ -> dialog.dismiss() }
                .attachAlphaSlideBar(true)
                .attachBrightnessSlideBar(false)
                .setBottomSpace(12) // set a bottom space between the last slidebar and buttons.
            colorPickerDialog.colorPickerView.setInitialColor(Color.BLACK)
            colorPickerDialog.show()
```
`envelope` in `onColorSelected` would always return #FF000000 although I'm selecting different colors like Red,Yellow,etc
This is happening if I set the initial color to Black (Color.BLACK), doesn't happen if the initial color are colors like Color.RED / Color.YELLOW

**Comment by skydoves** [comment]
Hi, @illwiz 
That is the expected result. Because the value of the brightness is 0 (the darkest value), every color's brightness will be black too.
You will always get black color if you change the brightness to the darkest value manually.

**Comment by illwiz** [comment]
Yep, sorry didn't notice that back then
