### ISSUE TITLE
setSelectorPoint() crashes the app

### ISSUE THREAD

**Issue by G33RY** [skydoves/ColorPickerView#68]
- Library Version [v2.2.3]
- Affected Device(s) [Emulator]
 
**Describe the Bug:**

When I want to set the selector point it crashes the app. 
I am using a custom color palette.

I tried with moveSelectorPoint but that's crashes it too.

The problem occurred on *ColorPickerView.java:418*

**Expected Behavior:**

It should set the selector's coordinate

**Comment by skydoves** [comment]
Hi, @G33RY
I just built using the [demo](https://github.com/skydoves/ColorPickerView/tree/master/app) project, it works well. 🤔 
Can you provide an example project or code? Even the line `418` seems hard to estimate where crashes from.

Line 417~419
```java
if (colorListener instanceof ColorListener) {
    ((ColorListener) colorListener).onColorSelected(selectedColor, fromUser);
}
```

**Comment by G33RY** [comment]
Okay, I solved it sorry. 

The view didn't rendered completely and I wanted to set the position so it created a infinite loop somehow and that was crashing the app. 

Now I put the setter in a listener which activates when the color picker view fully rendered.
