### ISSUE TITLE
Can I get color after moved (ACTION_UP)?

### ISSUE THREAD

**Issue by vurvn** [skydoves/ColorPickerView#7]

**Comment by skydoves** [comment]
By using setColorListener, you can get color when ACTION_DOWN and ACTION_MOVE.

```java
colorPickerView.setColorListener(new ColorListener() {
            @Override
            public void onColorSelected(int color) {
                LinearLayout linearLayout = findViewById(R.id.linearLayout);
                linearLayout.setBackgroundColor(color);
            }
        });
```
and you can get color using getColor() method.

**Comment by vurvn** [comment]
I used it. But in my app, everytime color change it will send request to server. It's too many. So I want to get only one color after user moved selector. I mean user's finger not on screen anymore (ACTION_UP). I tried colorPickerView.setOnTouchListener to detect MotionEvent.ACTION_UP but it not work :(  Can I make selector don't move & just touch down to get color?

**Comment by skydoves** [comment]
Oh I see.
I'm going to add ACTION_UP mode soon :)
Thank your opinion!

**Comment by vurvn** [comment]
Thank you for your quick reply. :)

**Comment by skydoves** [comment]
Hi,
Now you can use setAction\_UP method version 1.0.8.

setACTION_UP(Boolean) | void | ColorListener only listening when ACTION_UP.
-- | -- | --

**Comment by vurvn** [comment]
Awesome. Thank you so much.
