### ISSUE TITLE
Selector Drawable Color and Icon Change.

### ISSUE THREAD

**Issue by HafizAwaiskhan** [skydoves/ColorPickerView#70]
We should add selector drawable as we want and it should show color where we move it. Right now Bubble flag is performing that functionality but i want to do it with selector drawable.

**Comment by skydoves** [comment]
Hi, @HafizAwaiskhan  
I wonder that how can we distinguish the selector if the color of the selector drawable is the same as the selected (background) color?

**Comment by HafizAwaiskhan** [comment]
There can be many possibilities ,  as you have done with bubble flag we can do the same with Selector.
we can add boarder like bubble flag

**Comment by HafizAwaiskhan** [comment]
Actually i want this kind of circular color picker or color picking property is this possible ?
https://2672686a4cf38e8c2458-2712e00ea34e3076747650c92426bbb5.ssl.cf1.rackcdn.com/2018-05-20-06-00-23.jpeg

**Comment by skydoves** [comment]
I see. Actually, we can implement it a trick way: set the selector as a small and transparent drawable and applying color changes to the bubble. But someone created PR #71 for accessing the selector. After merging this PR, you can implement that without the bubble.

**Comment by HafizAwaiskhan** [comment]
Yes i have done that but after doing that i got a new issue.
https://drive.google.com/drive/folders/1Jx-zs3MNje92TrVdsskZQQ6COsxLNK9H?usp=sharing

**Comment by skydoves** [comment]
Here is a method:

```java
flag.setFlipAble(false)
```

**Comment by HafizAwaiskhan** [comment]
Not working ..... I have applied this property but its getting ever worst.
bubble is not moving on upper side of pallate

**Comment by skydoves** [comment]
@HafizAwaiskhan Thank you for your checking!
That seems a bug (the flag cannot move over position 0 of the Y).
I just released a new version `2.2.4-SNAPSHOT` please include the snapshot on your project following the [guides](https://github.com/skydoves/colorpickerview#snapshot) and check the `setFlipAble(false)` works correctly.
Also, I just added `flag_isFlipAble` attribute to call the method directly on your XML file.
Thanks !

**Comment by HafizAwaiskhan** [comment]
thank you so much for all of this :)

**Comment by HafizAwaiskhan** [comment]
@skydoves  have you done that changing ?
i am trying but there is no change in your project still working same after adding 2.2.4-SNAPSHOT

**Comment by skydoves** [comment]
`2.2.4.1-SNAPSHOT` has been released. 
You can use `getSelector()` method newly.
Thanks :)

**Comment by skydoves** [comment]
Hey @HafizAwaiskhan, have you checked the new version works correctly?

**Comment by HafizAwaiskhan** [comment]
yes All the things are working fine :)
thank you so much

**Comment by HafizAwaiskhan** [comment]
@skydoves 
one more problem i am facing 
I am changing the color of Pallet like 2 or three color pallet , But when i move Selector and flag shows me the other colors.
https://drive.google.com/file/d/1grrcTYyZMl0fFCk3NqqG8XX_b-WY9nhY/view?usp=sharing

You can see in this picture i have two color pallet and my Selector is on top but it showing me green color instead of original color .

**Comment by skydoves** [comment]
Resolved by the recent release.
