### ISSUE TITLE
ColorPicker.setInitialColor issue

### ISSUE THREAD

**Issue by HafizAwaiskhan** [skydoves/ColorPickerView#74]
- Library Version [e.g. v 1.0]
@skydoves 
 
**Describe the Bug:**
I am using an Image Drawable and set Its Initial Color but its is not showing the flag on that place where it should show .
public void setPaletteDrawable(Drawable drawable){
//Choosing image from Drawable
}

public void setInitialColor(@ColorInt final int color) {
}

**Expected Behavior:**

we can choose any Image from Drawable and when we will call setInitialColor() method it should show the exact position on Drawable. 
the Drawable I am using 
https://drive.google.com/file/d/1B5R4irIsAmELmlPzHp4QE3mJYtK1_WsU/view?usp=sharing

**Comment by HafizAwaiskhan** [comment]
@yccheok

**Comment by skydoves** [comment]
`setInitialColor` will not work correctly If you are using a custom drawable palette.

> This method will not work if the default palette drawable is not {@link ColorHsvPalette}.
