### ISSUE TITLE
Image drawable palette does not map initial color accurate

### ISSUE THREAD

**Issue by mhassaan07** [skydoves/ColorPickerView#75]
I am using an image as a drawable on the palette. When I am trying to set the **initial color** property it does not map the selector to the right color.

Please fix this issue.

**Comment by skydoves** [comment]
Hi, could you share which version do you use?

**Comment by mhassaan07** [comment]
I am using this version.
2.2.4-SNAPSHOT

**Comment by skydoves** [comment]
initial color only works with the default HSV drawble.
