### ISSUE TITLE
Initial color not showing in default color pickerview

### ISSUE THREAD

**Issue by pgandroid1289** [skydoves/ColorPickerView#78]
- Library Version v2.2.3
- Affected Device(s) - MI Note 7 Pro with Android 10
 
**Describe the Bug:**

I want default dark grey color in color picker pattele. For that i have set 

` <com.skydoves.colorpickerview.ColorPickerView
                        android:id="@+id/colorPickerView"
                        android:layout_width="match_parent"
                        android:layout_height="300dp"
                        android:layout_gravity="center"
                        android:layout_margin="16dp"
                        app:preferenceName="Test2"
                        app:initialColor="@color/dark_grey"
                        app:selector="@drawable/wheel" />`

but this is not setting as a default color to color picker view. 

**Expected Behavior:**

Right now this is not working and i am getting _#AEAEAE_ different color code and rgb color respectively different.

A clear description of what you expected to happen.

I want when color picker view loads then selector will be on point of my dark grey color. From it i want to get rgb color and hash color from dark grey color.

@skydoves

**Comment by skydoves** [comment]
Hi @pgandroid1289,
Sorry for the delayed response. Could you check this work with #77?
