### ISSUE TITLE
Initilize ColorPickerView

### ISSUE THREAD

**Issue by ShubhamSoni** [skydoves/ColorPickerView#8]
I am trying to use ColorPickerView to pick colors and save it to preference. Next time when I open the selector activity I want it to show previously saved color. I am not sure how this can be done when we do not have any API that allows to initialize ColorPickerView.

**Comment by skydoves** [comment]
You means about "initialize ColorPickerView" is initializing selector's position?

**Comment by ShubhamSoni** [comment]
No not the selection position but, with an initial color. I think it is not possible as a palette can be changed. What I was looking for was a way to set a color value. For example last time I picked #FF00FF color and closed the picker and saved the value to a preference. Now when I open the app again I read the color value and set it to picket again but, I think that I'll need to store the point and set it on picker on startup.

**Comment by skydoves** [comment]
oh, I see. your meaning was processing following procedure.
1. save colorpickverView's status
2. restore colorpickverView's status
3. fire selector's click event.
without any other API like SharedPreference.
Is it right?

**Comment by skydoves** [comment]
I published ColorPickerPreference.
https://github.com/skydoves/ColorPickerPreference

**Comment by tombed631** [comment]
ColorPickerReferenence does not have Sliders (what i need is BrightnessSlider) so can you add to this projekct initPosition methods? I see only in init() setCenter() call... But it would be needed setter with params to set initial position... 

I need both of saving colors and brithnessSlider. Im looking forward for your reply.

**Comment by skydoves** [comment]
#19
