### ISSUE TITLE
ActionMode and FlagMode aren't working independently

### ISSUE THREAD

**Issue by janaltenhof** [skydoves/ColorPickerView#80]
- Library Version 2.2.3
 
**Describe the Bug:**

When I set ColorPickerView's ActionMode to LAST it works as it should. But I want the FlagView to move together with the Selector so I set it to FlagMode.ALWAYS. 
But there is a Bug that FlagMode.ALWAYS has no effect when you set your ColorPickerView to LAST.

**Expected Behavior:**

ActionMode and FlagMode should be working independent from each other.

I already tried to fix this in your sample app. See the attached videos please.

**Unexpected Behavior**
https://user-images.githubusercontent.com/51320528/142865610-b039e7e9-40d2-47c0-b424-8e9b700f0e6b.mp4

**Expected Behavior**
https://user-images.githubusercontent.com/51320528/142866047-1654e9b5-1246-4c8f-b645-24eac1790675.mp4

**Comment by skydoves** [comment]
`2.2.4-SNAPSHOT` has been released.

**Comment by janaltenhof** [comment]
Thank you! Works great. 
Do you know when you can release it to maven central?

**Comment by skydoves** [comment]
`2.2.4` stable has been released. 🎉
