### ISSUE TITLE
How to use ColorPickerDialog.Builder in a service?

### ISSUE THREAD

**Issue by Harshkanani** [skydoves/ColorPickerView#82]
- Library Version [v2.2.4]

Giving me the below error when using it in a service. I tried passing everthing as a context but nothing worked.
Error : java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

It works fine in activity

**Comment by skydoves** [comment]
Sorry for the delayed response. I don't understand this issue, because Service can not contain UI-relevant things.
If you have more details, please reopen and expand on this. Thanks!
