### ISSUE TITLE
How to make the selector slide no more than the ColorPickerView?

### ISSUE THREAD

**Issue by hexianqiao3755** [skydoves/ColorPickerView#83]
@skydoves Hi, Can the selector slide to no more than ColorPickerView?
![image](https://user-images.githubusercontent.com/12272540/145513859-cb968036-d8ec-40fe-b7dc-8a18b15e9716.png)
![image](https://user-images.githubusercontent.com/12272540/145513886-2c2a8b9b-bd27-48ea-9972-44ccd8281dd7.png)

**Comment by Deaful** [comment]
@skydoves Hi, could you let the selector stay inside of the circle palette boundary？

![取色器](https://user-images.githubusercontent.com/25816100/191669990-0f5afdd7-3941-4f4c-9b61-bf6cc0f9bb00.png)

This is the original images of selector drawable. And I don't change palette's settings.

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:innerRadius="11dp"
    android:shape="ring"
    android:thickness="2dp"
    android:useLevel="false">
    <stroke
        android:width="2dp"
        android:color="@color/white" />
</shape>

<com.skydoves.colorpickerview.ColorPickerView
    android:id="@+id/colorPickerView"
    android:layout_width="140dp"
    android:layout_height="140dp"
    app:actionMode="last"
    app:selector="@drawable/selector_color"
    app:selector_size="30dp"
    android:layout_gravity="center" />

**Comment by skydoves** [comment]
Hey guys, sorry for the very delayed response. I don't have plans to resolve this programmatically, instead, you can use an image, which includes some paddings. Thanks for reporting this issue!
