### ISSUE TITLE
Illegal char <:> at index 53: app-mergeDebugResources-38:/values/values.xml

### ISSUE THREAD

**Issue by Dhanrajsinh002** [skydoves/ColorPickerView#91]
- Library Version 2.2.4
- Affected Device(s) Redmi Note 5
- I'm using Android Studio Chipmunk | 2021.2.1 Patch 1
 
**Illegal char <:> at index 53 in values.xml file:**

In may application i'm custom color picker dialog. for that i have used this library (skydoves/ColorPickerView) with latest version with 2.2.4. And when I try to **Run 'app'** it is showing **Illegal char <:> at index 53: com.example.myapp.app-mergeDebugResources-38:/values/values.xml** error. before that I have used another colorpickerdialog library and that was works fine. No errors like this are there. Also, I check that in my project there no values/values.xml kind of file.

**Comment by Dhanrajsinh002** [comment]
- I used Android Studio Chipmunk | 2021.2.1 Patch 1

**Comment by skydoves** [comment]
Hey, thank you for reporting this issue. Could you please check if this issue is not happening in version `2.2.3`?

**Comment by Dhanrajsinh002** [comment]
Yes, Same error

**Comment by skydoves** [comment]
I don't think this issue is related to this library. I recommend building your project after cleaning or updating your Gradle/Compile, Target SDK/AGP versions.

**Comment by Equin** [comment]
i have same error when added this lib to dependencies 
Illegal char <:> at index 46: co.roomapp.klassroom.app-mergeDebugResources-5:/values/values.xml
