### ISSUE TITLE
Jitpack.io is broken

### ISSUE THREAD

**Issue by hannesa2** [skydoves/ColorPickerView#95]
https://jitpack.io/#skydoves/ColorPickerView here the last version `2.2.4` doesn't build anymore https://jitpack.io/com/github/skydoves/ColorPickerView/2.2.4/build.log

![image](https://user-images.githubusercontent.com/3314607/223731024-500b8a8b-4593-48fd-94f8-8f8f93385ea6.png)

**Comment by skydoves** [comment]
As I described in #96, you should download this on Maven Central, not Jitpack.
